In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from random import randint
import numpy as np
import pandas as pd 
import torch.optim as optim
import os
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import Dataset
import torch
from scipy.stats import vonmises
res = 36

In [96]:
class CircleNet(nn.Sequential): 
    def __init__(self, res, dropout, n_out): 
        super(CircleNet, self).__init__()
        self.n_in = res
        self.affine1 = nn.Linear(self.n_in, self.n_in//18)
        self.drop1 = nn.Dropout(dropout)
        ##self.affine2 = nn.Linear(self.n_in//2, self.n_in//2)
        ##self.drop2 = nn.Dropout(dropout)
        self.affine3 = nn.Linear(self.n_in//18, n_out)
    def forward(self, x): 
        x = F.relu(self.affine1(x))
        x = self.drop1(x)
        ##x = F.relu(self.affine2(x))
        ##x = self.drop2(x)
        x = F.relu(self.affine3(x))
        x = F.softmax(x, dim = 1)
        return x

In [29]:
## make some uniform circular data
res = 36
num_points = 100
num_samples = 1000
data = np.zeros([num_points,res + 1])
for i in range(num_points): 
    for j in range(num_samples): 
        num = randint(0,res-1)
        data[i][num]+= 1
        data[i][res] = -1
np.savetxt("uniform1testdata.csv", data, delimiter = ",")

In [11]:
##reads the data back into a numpy array
data2 = pd.read_csv("uniform.csv")
data2array = data2.values

array([32., 33., 23., 26., 28., 27., 25., 40., 26., 33., 20., 25., 25.,
       25., 31., 34., 32., 28., 26., 22., 23., 32., 28., 25., 37., 18.,
       33., 20., 23., 26., 36., 24., 26., 37., 20., 31.])

In [15]:
##This is a class that allows us to load data from csv files and make them into datasets that the dataloader can use
class CircularDataset(Dataset): 
    def __init__(self, data_root): 
        self.data = []
        self.dist_coder = LabelEncoder()
        self.dist_list = []
        for path in data_root: 
            array = pd.read_csv(path)
            
            self.dist_list += [array.values[0,-1]] ##get the distribution type for each file and add it to the list
            if len(self.data) == 0: 
                self.data = array.values
            else:
                print(self.data.shape)
                print(array.values.shape)
                self.data = np.concatenate((self.data,array.values), axis = 0)
                
               
        
        self.dist_coder.fit(self.dist_list)
      
    def __getitem__(self,idx): 
        return self.data[idx][0:-1], self.to_one_hot(self.dist_coder,([self.data[idx,-1]]))[0]
    def __len__(self): 
        return len(self.data)
    
    def to_one_hot(self, codec, values):
        value_idxs = codec.transform(values)
        return torch.eye(len(codec.classes_))[value_idxs]

In [244]:
[1,2,3][0:-1]

[1, 2]

In [281]:
dataset = CircularDataset(["uniformtest1.csv", "uniformtest2.csv"])

(999, 37)
(999, 37)


In [246]:
dataset.__getitem__(0)

(array([22., 28., 33., 27., 22., 30., 28., 30., 25., 27., 27., 26., 24.,
        25., 29., 27., 30., 25., 25., 28., 28., 28., 25., 24., 32., 24.,
        31., 31., 40., 30., 27., 27., 23., 28., 33., 31.]), tensor([0., 1.]))

In [247]:
iterator = torch.utils.data.DataLoader(dataset, batch_size = 2, shuffle = True)

In [248]:
for data, label in iterator: 
    
    print(label)

tensor([[1., 0.],
        [1., 0.]])
tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 1.],
        [1., 0.]])
tensor([[0., 1.],
        [1., 0.]])
tensor([[0., 1.],
        [1., 0.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[0., 1.],
        [1., 0.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[0., 1.],
        [1., 0.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0., 1.],
        [1., 0.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0., 1.],
        [1., 0.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[0., 1.],
        [1., 0.]])
tensor([[0., 1.],
        [0., 1.]])
t

        [0., 1.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[0., 1.],
        [1., 0.]])
tensor([[0., 1.],
        [1., 0.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[0., 1.],
        [1., 0.]])
tensor([[1., 0.],
        [0., 1.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0., 1.],
        [1., 0.]])
tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 1.],
        [1., 0.]])
tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[1., 0.],
        [0., 1.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0., 1.],
 

        [0., 1.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 1.],
        [1., 0.]])
tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[0., 1.],
        [1., 0.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 1.],
        [1., 0.]])
tensor([[1., 0.],
        [0., 1.]])
tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 1.],
        [0., 1.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0., 1.],
        [1., 0.]])
tensor([[1., 0.],
 

In [97]:
rate = .002
batchsize = 10
dataset = CircularDataset(["uniformtest1.csv", "vonmises4.csv"])
testdata = CircularDataset(["uniform1testdata.csv", "vonmises4test.csv"])
iterator = torch.utils.data.DataLoader(dataset, batch_size = batchsize, shuffle = True)
testiterator = torch.utils.data.DataLoader(testdata, batch_size = batchsize, shuffle = True)
net = CircleNet(36,0,2)
optimizer = optim.Adam(net.parameters(),lr = rate)
running_loss = 0
epochs = 8

net.train()
loss_func = nn.CrossEntropyLoss()
for e in range(epochs): 
    print(running_loss)
    running_loss = 0
    accuracy = 0
    i = 0
    for dist, labels in iterator: 
        
        
        
        optimizer.zero_grad()
        out = net(dist.float()/100)
        
        loss = loss_func(out,torch.max(labels, 1)[1])
       
           
        loss.backward()
        optimizer.step()
        running_loss += loss
    for dist, labels in testiterator: 
        ps = net(dist.float()/100)
        i += 1
        top_p, top_class = ps.topk(1, dim=1)
       
        top_p2, top_class2 = labels.topk(1, dim = 1)
        
        equals = top_class == top_class2
        
        accuracy += torch.sum(equals.float())
        
    accuracy = accuracy/i/batchsize
    print(accuracy)
    accuracy = 0
    

(999, 37)
(999, 37)
(99, 37)
(99, 37)
0
tensor(0.7000)
tensor(136.5262, grad_fn=<AddBackward0>)
tensor(0.7050)
tensor(127.6327, grad_fn=<AddBackward0>)
tensor(0.8000)
tensor(116.3390, grad_fn=<AddBackward0>)
tensor(0.8400)
tensor(106.6592, grad_fn=<AddBackward0>)
tensor(0.8950)
tensor(98.9182, grad_fn=<AddBackward0>)
tensor(0.9200)
tensor(92.4964, grad_fn=<AddBackward0>)
tensor(0.9450)
tensor(87.1380, grad_fn=<AddBackward0>)
tensor(0.9500)


In [77]:
for dist, labels in iterator: 
    out = net(dist.float()/100)
    print( str(out) + " True: " + str(labels) + "\n")

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.9688, 0.0312],
        [0.9978, 0.0022],
        [0.9958, 0.0042],
        [0.5000, 0.5000],
        [0.9963, 0.0037],
        [0.9983, 0.0017],
        [0.5000, 0.5000],
        [0.6175, 0.3825]], grad_fn=<SoftmaxBackward>) True: tensor([[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.]])

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5216, 0.4784],
        [0.9942, 0.0058],
        [0.5000, 0.5000],
        [0.5307, 0.4693],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.]])

tensor([[0.5000, 0.5000],
        [0.5000, 0.500


tensor([[0.7219, 0.2781],
        [0.9981, 0.0019],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.9936, 0.0064],
        [0.5000, 0.5000],
        [0.8327, 0.1673],
        [0.5177, 0.4823],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.]])

tensor([[0.5000, 0.5000],
        [0.9950, 0.0050],
        [0.9952, 0.0048],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.9562, 0.0438],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.]])

tensor([[0.9974, 0.0026],
        [0.5000, 0.50


tensor([[0.6609, 0.3391],
        [0.5000, 0.5000],
        [0.9911, 0.0089],
        [0.9984, 0.0016],
        [0.5645, 0.4355],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.8657, 0.1343],
        [0.6086, 0.3914]], grad_fn=<SoftmaxBackward>) True: tensor([[0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.]])

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.9980, 0.0020],
        [0.5708, 0.4292],
        [0.9963, 0.0037],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.9968, 0.0032],
        [0.5737, 0.4263]], grad_fn=<SoftmaxBackward>) True: tensor([[1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.]])

tensor([[0.5936, 0.4064],
        [0.5000, 0.50


tensor([[0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.9953, 0.0047],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5351, 0.4649],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.]])

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.9723, 0.0277],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5002, 0.4998],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]])

tensor([[0.5345, 0.4655],
        [0.5000, 0.50


tensor([[0.5085, 0.4915],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5218, 0.4782],
        [0.5000, 0.5000],
        [0.5046, 0.4954],
        [0.5563, 0.4437],
        [0.9638, 0.0362],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.]])

tensor([[0.5000, 0.5000],
        [0.9834, 0.0166],
        [0.5000, 0.5000],
        [0.5114, 0.4886],
        [0.5598, 0.4402],
        [0.5534, 0.4466],
        [0.9773, 0.0227],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.]])

tensor([[0.5000, 0.5000],
        [0.5347, 0.46


tensor([[0.9944, 0.0056],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.6154, 0.3846],
        [0.9930, 0.0070],
        [0.5743, 0.4257],
        [0.9980, 0.0020],
        [0.9979, 0.0021],
        [0.5000, 0.5000],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.]])

tensor([[0.9978, 0.0022],
        [0.6386, 0.3614],
        [0.5055, 0.4945],
        [0.6111, 0.3889],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.]])

tensor([[0.5763, 0.4237],
        [0.9973, 0.00


tensor([[0.5948, 0.4052],
        [0.5000, 0.5000],
        [0.5088, 0.4912],
        [0.9954, 0.0046],
        [0.5000, 0.5000],
        [0.5023, 0.4977],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]])

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.9841, 0.0159],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.9967, 0.0033],
        [0.9982, 0.0018],
        [0.5000, 0.5000],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.]])

tensor([[0.5000, 0.5000],
        [0.5505, 0.44


tensor([[0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.7507, 0.2493]], grad_fn=<SoftmaxBackward>) True: tensor([[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.]])

tensor([[0.5000, 0.5000],
        [0.6959, 0.3041],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5388, 0.4612],
        [0.5388, 0.4612],
        [0.5011, 0.4989],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]])

tensor([[0.5000, 0.5000],
        [0.5000, 0.50


tensor([[0.6980, 0.3020],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.9853, 0.0147],
        [0.5928, 0.4072],
        [0.5421, 0.4579],
        [0.5000, 0.5000],
        [0.9418, 0.0582],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.]])

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5272, 0.4728],
        [0.5000, 0.5000],
        [0.5917, 0.4083],
        [0.5552, 0.4448],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.]])

tensor([[0.5000, 0.5000],
        [0.5000, 0.50


tensor([[0.5000, 0.5000],
        [0.9978, 0.0022],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5069, 0.4931],
        [0.7636, 0.2364],
        [0.5577, 0.4423],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5166, 0.4834],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]])

tensor([[0.5000, 0.5000],
        [0.5000, 0.50


tensor([[0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.9978, 0.0022],
        [0.9981, 0.0019],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.9985, 0.0015],
        [0.5000, 0.5000],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.]])

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.9803, 0.0197],
        [0.5000, 0.5000],
        [0.5376, 0.4624],
        [0.5710, 0.4290],
        [0.5000, 0.5000],
        [0.5032, 0.4968],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]])

tensor([[0.5517, 0.4483],
        [0.5000, 0.50


tensor([[0.9888, 0.0112],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.5255, 0.4745],
        [0.5000, 0.5000],
        [0.5000, 0.5000],
        [0.9960, 0.0040],
        [0.5508, 0.4492],
        [0.5000, 0.5000],
        [0.5000, 0.5000]], grad_fn=<SoftmaxBackward>) True: tensor([[1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.]])

tensor([[0.9973, 0.0027],
        [0.5000, 0.5000],
        [0.9542, 0.0458],
        [0.7091, 0.2909],
        [0.8281, 0.1719],
        [0.9874, 0.0126],
        [0.5031, 0.4969],
        [0.9975, 0.0025]], grad_fn=<SoftmaxBackward>) True: tensor([[1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.]])



In [78]:
data = np.zeros([100,37])
for i in range(100):
    SAMPLE_SIZE = 1000
    kappa = 1
    vm_dist = vonmises.rvs(kappa, size=SAMPLE_SIZE)
    vm_dist = (vm_dist + np.pi)/(2*np.pi)*360//10
    
    for k in range(SAMPLE_SIZE):
        data[i][int(vm_dist[k])] += 1
    
    rotate_amt = randint(0,res - 1)
    data[i,0:-1] = rotate(data[i,0:-1], rotate_amt)
    data[i,-1] = -3
    

In [31]:
np.savetxt("vonmises4test.csv", data, delimiter = ",")

In [275]:
print(data[0])

[13.  5.  8.  8. 15. 13. 14. 12. 17. 28. 24. 33. 32. 47. 52. 51. 52. 51.
 74. 80. 48. 46. 44. 44. 36. 33. 24. 10. 22. 11.  9.  9. 11.  8.  6. 10.
 -3.]


In [11]:
def rotate(vec, num_rotations): 
    vec2 = np.zeros(len(vec))
    for i in range(len(vec)): 
        vec2[(i + num_rotations )% len(vec)] = vec[i]
    return vec2
        